// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: stream.proto
#ifndef GRPC_stream_2eproto__INCLUDED
#define GRPC_stream_2eproto__INCLUDED

#include "stream.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace simpleStream {

class SimpleStream final {
 public:
  static constexpr char const* service_full_name() {
    return "simpleStream.SimpleStream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::simpleStream::SendRequest>> ServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::simpleStream::SendRequest>>(ServerUploadRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::simpleStream::SendRequest>> AsyncServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::simpleStream::SendRequest>>(AsyncServerUploadRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::simpleStream::SendRequest>> PrepareAsyncServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::simpleStream::SendRequest>>(PrepareAsyncServerUploadRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::simpleStream::RecvResponse>> ClientDownload(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::simpleStream::RecvResponse>>(ClientDownloadRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::simpleStream::RecvResponse>> AsyncClientDownload(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::simpleStream::RecvResponse>>(AsyncClientDownloadRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::simpleStream::RecvResponse>> PrepareAsyncClientDownload(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::simpleStream::RecvResponse>>(PrepareAsyncClientDownloadRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::ClientWriteReactor< ::simpleStream::SendRequest>* reactor) = 0;
      #else
      virtual void ServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::experimental::ClientWriteReactor< ::simpleStream::SendRequest>* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ClientDownload(::grpc::ClientContext* context, ::simpleStream::RecvRequest* request, ::grpc::ClientReadReactor< ::simpleStream::RecvResponse>* reactor) = 0;
      #else
      virtual void ClientDownload(::grpc::ClientContext* context, ::simpleStream::RecvRequest* request, ::grpc::experimental::ClientReadReactor< ::simpleStream::RecvResponse>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientWriterInterface< ::simpleStream::SendRequest>* ServerUploadRaw(::grpc::ClientContext* context, ::simpleStream::SendResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::simpleStream::SendRequest>* AsyncServerUploadRaw(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::simpleStream::SendRequest>* PrepareAsyncServerUploadRaw(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::simpleStream::RecvResponse>* ClientDownloadRaw(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::simpleStream::RecvResponse>* AsyncClientDownloadRaw(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::simpleStream::RecvResponse>* PrepareAsyncClientDownloadRaw(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientWriter< ::simpleStream::SendRequest>> ServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::simpleStream::SendRequest>>(ServerUploadRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::simpleStream::SendRequest>> AsyncServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::simpleStream::SendRequest>>(AsyncServerUploadRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::simpleStream::SendRequest>> PrepareAsyncServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::simpleStream::SendRequest>>(PrepareAsyncServerUploadRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::simpleStream::RecvResponse>> ClientDownload(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::simpleStream::RecvResponse>>(ClientDownloadRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::simpleStream::RecvResponse>> AsyncClientDownload(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::simpleStream::RecvResponse>>(AsyncClientDownloadRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::simpleStream::RecvResponse>> PrepareAsyncClientDownload(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::simpleStream::RecvResponse>>(PrepareAsyncClientDownloadRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::ClientWriteReactor< ::simpleStream::SendRequest>* reactor) override;
      #else
      void ServerUpload(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::experimental::ClientWriteReactor< ::simpleStream::SendRequest>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ClientDownload(::grpc::ClientContext* context, ::simpleStream::RecvRequest* request, ::grpc::ClientReadReactor< ::simpleStream::RecvResponse>* reactor) override;
      #else
      void ClientDownload(::grpc::ClientContext* context, ::simpleStream::RecvRequest* request, ::grpc::experimental::ClientReadReactor< ::simpleStream::RecvResponse>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientWriter< ::simpleStream::SendRequest>* ServerUploadRaw(::grpc::ClientContext* context, ::simpleStream::SendResponse* response) override;
    ::grpc::ClientAsyncWriter< ::simpleStream::SendRequest>* AsyncServerUploadRaw(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::simpleStream::SendRequest>* PrepareAsyncServerUploadRaw(::grpc::ClientContext* context, ::simpleStream::SendResponse* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::simpleStream::RecvResponse>* ClientDownloadRaw(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request) override;
    ::grpc::ClientAsyncReader< ::simpleStream::RecvResponse>* AsyncClientDownloadRaw(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::simpleStream::RecvResponse>* PrepareAsyncClientDownloadRaw(::grpc::ClientContext* context, const ::simpleStream::RecvRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ServerUpload_;
    const ::grpc::internal::RpcMethod rpcmethod_ClientDownload_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ServerUpload(::grpc::ServerContext* context, ::grpc::ServerReader< ::simpleStream::SendRequest>* reader, ::simpleStream::SendResponse* response);
    virtual ::grpc::Status ClientDownload(::grpc::ServerContext* context, const ::simpleStream::RecvRequest* request, ::grpc::ServerWriter< ::simpleStream::RecvResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_ServerUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ServerUpload() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ServerUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::simpleStream::SendRequest>* /*reader*/, ::simpleStream::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestServerUpload(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::simpleStream::SendResponse, ::simpleStream::SendRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ClientDownload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ClientDownload() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ClientDownload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientDownload(::grpc::ServerContext* /*context*/, const ::simpleStream::RecvRequest* /*request*/, ::grpc::ServerWriter< ::simpleStream::RecvResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClientDownload(::grpc::ServerContext* context, ::simpleStream::RecvRequest* request, ::grpc::ServerAsyncWriter< ::simpleStream::RecvResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ServerUpload<WithAsyncMethod_ClientDownload<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ServerUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ServerUpload() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::simpleStream::SendRequest, ::simpleStream::SendResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::simpleStream::SendResponse* response) { return this->ServerUpload(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_ServerUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::simpleStream::SendRequest>* /*reader*/, ::simpleStream::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::simpleStream::SendRequest>* ServerUpload(
      ::grpc::CallbackServerContext* /*context*/, ::simpleStream::SendResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::simpleStream::SendRequest>* ServerUpload(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::simpleStream::SendResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ClientDownload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ClientDownload() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::simpleStream::RecvRequest, ::simpleStream::RecvResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::simpleStream::RecvRequest* request) { return this->ClientDownload(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_ClientDownload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientDownload(::grpc::ServerContext* /*context*/, const ::simpleStream::RecvRequest* /*request*/, ::grpc::ServerWriter< ::simpleStream::RecvResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::simpleStream::RecvResponse>* ClientDownload(
      ::grpc::CallbackServerContext* /*context*/, const ::simpleStream::RecvRequest* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::simpleStream::RecvResponse>* ClientDownload(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::simpleStream::RecvRequest* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_ServerUpload<ExperimentalWithCallbackMethod_ClientDownload<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_ServerUpload<ExperimentalWithCallbackMethod_ClientDownload<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ServerUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ServerUpload() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ServerUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::simpleStream::SendRequest>* /*reader*/, ::simpleStream::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ClientDownload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ClientDownload() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ClientDownload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientDownload(::grpc::ServerContext* /*context*/, const ::simpleStream::RecvRequest* /*request*/, ::grpc::ServerWriter< ::simpleStream::RecvResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ServerUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ServerUpload() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ServerUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::simpleStream::SendRequest>* /*reader*/, ::simpleStream::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestServerUpload(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ClientDownload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ClientDownload() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ClientDownload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientDownload(::grpc::ServerContext* /*context*/, const ::simpleStream::RecvRequest* /*request*/, ::grpc::ServerWriter< ::simpleStream::RecvResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClientDownload(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ServerUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ServerUpload() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->ServerUpload(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ServerUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::simpleStream::SendRequest>* /*reader*/, ::simpleStream::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* ServerUpload(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* ServerUpload(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ClientDownload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ClientDownload() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->ClientDownload(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_ClientDownload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientDownload(::grpc::ServerContext* /*context*/, const ::simpleStream::RecvRequest* /*request*/, ::grpc::ServerWriter< ::simpleStream::RecvResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* ClientDownload(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* ClientDownload(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_ClientDownload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_ClientDownload() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::simpleStream::RecvRequest, ::simpleStream::RecvResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::simpleStream::RecvRequest, ::simpleStream::RecvResponse>* streamer) {
                       return this->StreamedClientDownload(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_ClientDownload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ClientDownload(::grpc::ServerContext* /*context*/, const ::simpleStream::RecvRequest* /*request*/, ::grpc::ServerWriter< ::simpleStream::RecvResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedClientDownload(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::simpleStream::RecvRequest,::simpleStream::RecvResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_ClientDownload<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_ClientDownload<Service > StreamedService;
};

}  // namespace simpleStream


#endif  // GRPC_stream_2eproto__INCLUDED
