// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AudioStream.proto
#ifndef GRPC_AudioStream_2eproto__INCLUDED
#define GRPC_AudioStream_2eproto__INCLUDED

#include "AudioStream.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace LiveStream {

class AudioStream final {
 public:
  static constexpr char const* service_full_name() {
    return "LiveStream.AudioStream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::LiveStream::DataStream>> AudioStreamReqeust(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::LiveStream::DataStream>>(AudioStreamReqeustRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::LiveStream::DataStream>> AsyncAudioStreamReqeust(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::LiveStream::DataStream>>(AsyncAudioStreamReqeustRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::LiveStream::DataStream>> PrepareAsyncAudioStreamReqeust(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::LiveStream::DataStream>>(PrepareAsyncAudioStreamReqeustRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void AudioStreamReqeust(::grpc::ClientContext* context, ::LiveStream::AudioFormat* request, ::grpc::ClientReadReactor< ::LiveStream::DataStream>* reactor) = 0;
      #else
      virtual void AudioStreamReqeust(::grpc::ClientContext* context, ::LiveStream::AudioFormat* request, ::grpc::experimental::ClientReadReactor< ::LiveStream::DataStream>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::LiveStream::DataStream>* AudioStreamReqeustRaw(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::LiveStream::DataStream>* AsyncAudioStreamReqeustRaw(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::LiveStream::DataStream>* PrepareAsyncAudioStreamReqeustRaw(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::LiveStream::DataStream>> AudioStreamReqeust(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::LiveStream::DataStream>>(AudioStreamReqeustRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::LiveStream::DataStream>> AsyncAudioStreamReqeust(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::LiveStream::DataStream>>(AsyncAudioStreamReqeustRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::LiveStream::DataStream>> PrepareAsyncAudioStreamReqeust(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::LiveStream::DataStream>>(PrepareAsyncAudioStreamReqeustRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void AudioStreamReqeust(::grpc::ClientContext* context, ::LiveStream::AudioFormat* request, ::grpc::ClientReadReactor< ::LiveStream::DataStream>* reactor) override;
      #else
      void AudioStreamReqeust(::grpc::ClientContext* context, ::LiveStream::AudioFormat* request, ::grpc::experimental::ClientReadReactor< ::LiveStream::DataStream>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::LiveStream::DataStream>* AudioStreamReqeustRaw(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request) override;
    ::grpc::ClientAsyncReader< ::LiveStream::DataStream>* AsyncAudioStreamReqeustRaw(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::LiveStream::DataStream>* PrepareAsyncAudioStreamReqeustRaw(::grpc::ClientContext* context, const ::LiveStream::AudioFormat& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AudioStreamReqeust_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AudioStreamReqeust(::grpc::ServerContext* context, const ::LiveStream::AudioFormat* request, ::grpc::ServerWriter< ::LiveStream::DataStream>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_AudioStreamReqeust : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AudioStreamReqeust() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AudioStreamReqeust() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AudioStreamReqeust(::grpc::ServerContext* /*context*/, const ::LiveStream::AudioFormat* /*request*/, ::grpc::ServerWriter< ::LiveStream::DataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAudioStreamReqeust(::grpc::ServerContext* context, ::LiveStream::AudioFormat* request, ::grpc::ServerAsyncWriter< ::LiveStream::DataStream>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AudioStreamReqeust<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AudioStreamReqeust : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_AudioStreamReqeust() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::LiveStream::AudioFormat, ::LiveStream::DataStream>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::LiveStream::AudioFormat* request) { return this->AudioStreamReqeust(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_AudioStreamReqeust() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AudioStreamReqeust(::grpc::ServerContext* /*context*/, const ::LiveStream::AudioFormat* /*request*/, ::grpc::ServerWriter< ::LiveStream::DataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::LiveStream::DataStream>* AudioStreamReqeust(
      ::grpc::CallbackServerContext* /*context*/, const ::LiveStream::AudioFormat* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::LiveStream::DataStream>* AudioStreamReqeust(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::LiveStream::AudioFormat* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_AudioStreamReqeust<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_AudioStreamReqeust<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AudioStreamReqeust : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AudioStreamReqeust() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AudioStreamReqeust() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AudioStreamReqeust(::grpc::ServerContext* /*context*/, const ::LiveStream::AudioFormat* /*request*/, ::grpc::ServerWriter< ::LiveStream::DataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AudioStreamReqeust : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AudioStreamReqeust() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AudioStreamReqeust() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AudioStreamReqeust(::grpc::ServerContext* /*context*/, const ::LiveStream::AudioFormat* /*request*/, ::grpc::ServerWriter< ::LiveStream::DataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAudioStreamReqeust(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AudioStreamReqeust : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_AudioStreamReqeust() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->AudioStreamReqeust(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_AudioStreamReqeust() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AudioStreamReqeust(::grpc::ServerContext* /*context*/, const ::LiveStream::AudioFormat* /*request*/, ::grpc::ServerWriter< ::LiveStream::DataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* AudioStreamReqeust(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* AudioStreamReqeust(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_AudioStreamReqeust : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_AudioStreamReqeust() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::LiveStream::AudioFormat, ::LiveStream::DataStream>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::LiveStream::AudioFormat, ::LiveStream::DataStream>* streamer) {
                       return this->StreamedAudioStreamReqeust(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_AudioStreamReqeust() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AudioStreamReqeust(::grpc::ServerContext* /*context*/, const ::LiveStream::AudioFormat* /*request*/, ::grpc::ServerWriter< ::LiveStream::DataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedAudioStreamReqeust(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::LiveStream::AudioFormat,::LiveStream::DataStream>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_AudioStreamReqeust<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_AudioStreamReqeust<Service > StreamedService;
};

}  // namespace LiveStream


#endif  // GRPC_AudioStream_2eproto__INCLUDED
